### ISSUE TITLE
select x words from a list of 100 words.

### ISSUE THREAD

**Issue by saeidalidadi** [saeidalidadi/python-course#7]
this should be a randomized selection.
so we should get a list from a file inside our app directory and select x words from it randomatically

**Comment by parvinsamin** [comment]
hi,
sorry i cant understand at all, you mean we should create file that keeps some words and also  have a function that read this file and return random word from this file ?

**Comment by saeidalidadi** [comment]
I see that you understand :)

**Comment by aartaa** [comment]
so we import random library and create the random function?
